name: SomtumMC
version: '1.0-bread'
main: fur.unityg.somtummc.SomtumMC
api-version: '1.20'
depend: [spark]
authors: [UnityG, Phapoom Saksri]
description: SomtumMC's Utility and Discord Bot!
website: https://somtum.fun
commands:
  rules:
    description: Rules Command.
    aliases:
      - rule
      - rules
      - imnotshutcre
    usage: /<command>
  gamemode:
    description: hai :3 its a gamemode cummand
    aliases:
      - gm
      - gammode
      - givemecreativenerd
    usage: /<command> [survival | creative | adventure | spectator]
    permission: somtum.gamemode
  sethome:
    description: sethome command
    aliases:
      - sethouse
      - seth
      - savehome
    usage: /<command>
  home:
    description: home command
    aliases:
      - house
      - hom
      - mybed
    usage: /<command>
  delhome:
    description: delhome command
    aliases:
      - deletehome
      - deletehouse
      - byebyehome
    usage: /<command>